version: '3.7'

services:
    hugo:
        image: klakegg/hugo:latest
        volumes:
            - ./hugo-site:/src
            - ./public:/target
        env_file: .env
        networks: [common]

    nginx:
        image: nginx:latest
        volumes:
            - ./public:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        env_file: .env
        networks: [net, common]
        depends_on:
            - hugo

volumes:
  hugo-site:
  public:

networks:
    net:
        external: true
    common:
        internal: true
